#!/usr/bin/env python3
"""Audit a repository for portable project-structure quality rules."""

from __future__ import annotations

import argparse
import fnmatch
import json
import os
from pathlib import Path
from typing import Iterable


SOURCE_EXTENSIONS = {
    ".c", ".cc", ".cpp", ".cs", ".fs", ".go", ".h", ".hpp", ".java",
    ".js", ".jsx", ".kt", ".kts", ".php", ".py", ".rb", ".rs", ".swift",
    ".ts", ".tsx", ".vb",
}
DEFAULT_IGNORES = {
    ".git", ".hg", ".svn", ".idea", ".vs", ".vscode", ".venv", "venv",
    "__pycache__", "node_modules", "vendor", "packages", "bin", "obj", "out",
    "dist", "build", "target", "coverage", "artifacts", "generated",
}
ROOT_SOURCE_ALLOWLIST = {
    "asgi.py", "conftest.py", "gulpfile.js", "manage.py", "setup.py", "wsgi.py",
}
ROOT_CONFIG_PATTERNS = (
    "*.config.js", "*.config.cjs", "*.config.mjs", "*.config.ts",
    "eslint.config.*", "next.config.*", "vite.config.*", "webpack.config.*",
)
GENERATED_MARKERS = ("<auto-generated", "@generated", "generated code", "do not edit")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("root", nargs="?", default=".", help="Project root to audit")
    parser.add_argument("--format", choices=("text", "json"), default="text")
    parser.add_argument("--warn-lines", type=int, default=500)
    parser.add_argument("--max-lines", type=int, default=800)
    parser.add_argument("--strict", action="store_true", help="Fail on warnings too")
    parser.add_argument(
        "--allow-root-source",
        action="append",
        default=[],
        metavar="NAME",
        help="Allow an additional source filename in the project root",
    )
    parser.add_argument(
        "--exclude",
        action="append",
        default=[],
        metavar="DIR",
        help="Ignore an additional directory name",
    )
    return parser.parse_args()


def finding(severity: str, code: str, path: str, message: str) -> dict[str, str]:
    return {"severity": severity, "code": code, "path": path, "message": message}


def detect_stacks(root: Path, ignored: set[str]) -> list[str]:
    stacks: list[str] = []
    names = {item.name.lower() for item in root.iterdir()} if root.exists() else set()
    files = [item for item in root.iterdir() if item.is_file()] if root.exists() else []
    source_extensions: set[str] = set()
    for current, directories, source_names in os.walk(root):
        directories[:] = [name for name in directories if name.lower() not in ignored]
        source_extensions.update(Path(name).suffix.lower() for name in source_names)
    if any(item.suffix.lower() in {".sln", ".csproj", ".fsproj", ".vbproj"} for item in files) or source_extensions.intersection({".cs", ".fs", ".vb"}):
        stacks.append(".NET")
    if "package.json" in names or source_extensions.intersection({".js", ".jsx", ".ts", ".tsx"}):
        stacks.append("Node/TypeScript")
    if names.intersection({"pyproject.toml", "setup.py", "requirements.txt", "poetry.lock"}) or ".py" in source_extensions:
        stacks.append("Python")
    if names.intersection({"pom.xml", "build.gradle", "build.gradle.kts", "settings.gradle"}) or source_extensions.intersection({".java", ".kt", ".kts"}):
        stacks.append("Java/Kotlin")
    if "go.mod" in names or ".go" in source_extensions:
        stacks.append("Go")
    if "cargo.toml" in names or ".rs" in source_extensions:
        stacks.append("Rust")
    return stacks or ["Unknown"]


def iter_source_files(root: Path, ignored: set[str]) -> Iterable[Path]:
    for current, directories, files in os.walk(root):
        directories[:] = [
            name for name in directories
            if name.lower() not in ignored and not name.startswith(".audit-project-")
        ]
        base = Path(current)
        for name in files:
            path = base / name
            if path.suffix.lower() in SOURCE_EXTENSIONS:
                yield path


def is_generated(path: Path) -> bool:
    try:
        with path.open("r", encoding="utf-8", errors="replace") as handle:
            head = "".join(handle.readline() for _ in range(8)).lower()
        return any(marker in head for marker in GENERATED_MARKERS)
    except OSError:
        return False


def line_count(path: Path) -> int:
    with path.open("rb") as handle:
        return sum(1 for _ in handle)


def root_source_allowed(path: Path, stacks: list[str], allowlist: set[str]) -> bool:
    lower = path.name.lower()
    if lower in allowlist or lower in ROOT_SOURCE_ALLOWLIST:
        return True
    if any(fnmatch.fnmatch(lower, pattern) for pattern in ROOT_CONFIG_PATTERNS):
        return True
    if path.suffix.lower() == ".go" and "Go" in stacks:
        return True
    return False


def has_tests(root: Path, ignored: set[str]) -> bool:
    test_directories = {"test", "tests", "__tests__"}
    for current, directories, files in os.walk(root):
        directories[:] = [name for name in directories if name.lower() not in ignored]
        if Path(current).name.lower() in test_directories:
            return True
        for name in files:
            lower = name.lower()
            if (
                lower.startswith("test_")
                or lower.endswith(("_test.py", ".test.js", ".test.ts", ".spec.js", ".spec.ts", "tests.cs"))
                or lower.endswith("_test.go")
            ):
                return True
    return False


def has_ci(root: Path) -> bool:
    workflows = root / ".github" / "workflows"
    if workflows.is_dir() and any(path.suffix.lower() in {".yml", ".yaml"} for path in workflows.iterdir()):
        return True
    return any((root / name).exists() for name in (".gitlab-ci.yml", "azure-pipelines.yml", "Jenkinsfile"))


def audit(args: argparse.Namespace) -> dict[str, object]:
    root = Path(args.root).expanduser().resolve()
    if not root.is_dir():
        raise SystemExit(f"Project root does not exist or is not a directory: {root}")
    if args.warn_lines <= 0 or args.max_lines <= args.warn_lines:
        raise SystemExit("--max-lines must be greater than --warn-lines, and both must be positive")

    ignored = {name.lower() for name in DEFAULT_IGNORES}
    ignored.update(name.lower() for name in args.exclude)
    allowlist = {name.lower() for name in args.allow_root_source}
    stacks = detect_stacks(root, ignored)
    findings: list[dict[str, str]] = []
    sources = list(iter_source_files(root, ignored))

    for path in sorted(sources):
        relative = path.relative_to(root).as_posix()
        if path.parent == root and not root_source_allowed(path, stacks, allowlist):
            findings.append(finding(
                "warning",
                "root-source",
                relative,
                "Business source is in the repository root; move it to the stack's conventional source directory or document an exception.",
            ))
        if is_generated(path):
            continue
        try:
            lines = line_count(path)
        except OSError as error:
            findings.append(finding("warning", "unreadable-source", relative, str(error)))
            continue
        if lines >= args.max_lines:
            findings.append(finding(
                "error",
                "large-file-limit",
                relative,
                f"{lines} lines exceeds the {args.max_lines}-line default limit; split by responsibility or document a justified exception.",
            ))
        elif lines >= args.warn_lines:
            findings.append(finding(
                "warning",
                "large-file-warning",
                relative,
                f"{lines} lines exceeds the {args.warn_lines}-line review threshold.",
            ))

    if not (root / ".editorconfig").is_file():
        findings.append(finding("warning", "missing-editorconfig", ".editorconfig", "No repository-level encoding and formatting baseline was found."))
    if not (root / "AGENTS.md").is_file():
        findings.append(finding("warning", "missing-agent-rules", "AGENTS.md", "No cross-Agent project quality rules were found."))
    if sources and not has_tests(root, ignored):
        findings.append(finding("warning", "missing-tests", "tests", "Source files were found but no conventional test directory or test filenames were detected."))
    if not has_ci(root):
        findings.append(finding("warning", "missing-ci", ".github/workflows", "No conventional CI pipeline was detected."))

    counts = {
        severity: sum(1 for item in findings if item["severity"] == severity)
        for severity in ("error", "warning", "info")
    }
    return {
        "root": str(root),
        "stacks": stacks,
        "source_files": len(sources),
        "thresholds": {"warning": args.warn_lines, "error": args.max_lines},
        "summary": counts,
        "findings": findings,
    }


def print_text(report: dict[str, object]) -> None:
    print(f"Project: {report['root']}")
    print(f"Stacks: {', '.join(report['stacks'])}")
    print(f"Source files: {report['source_files']}")
    findings = report["findings"]
    if not findings:
        print("PASS no project-quality findings")
        return
    for item in findings:
        print(f"{item['severity'].upper():7} {item['code']:22} {item['path']} - {item['message']}")
    summary = report["summary"]
    print(f"Summary: {summary['error']} error(s), {summary['warning']} warning(s)")


def main() -> int:
    args = parse_args()
    report = audit(args)
    if args.format == "json":
        print(json.dumps(report, ensure_ascii=False, indent=2))
    else:
        print_text(report)
    summary = report["summary"]
    return 1 if summary["error"] > 0 or (args.strict and summary["warning"] > 0) else 0


if __name__ == "__main__":
    raise SystemExit(main())
